### 상품 검색 API
GET http://localhost:8080/search?keyword=셔츠&page=0
Content-Type: application/json

### 상품 디테일 조회 API
GET http://localhost:8080/detail?productId=1
Content-Type: application/json

### 상품 Id로 옵션 및 재고 전체 조회 API
GET http://localhost:8080/variants-info?productId=1
Content-Type: application/json

### 상품 Id로 옵션만 전체 조회 API
GET http://localhost:8080/variants?productId=1
Content-Type: application/json
